apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2023-11-13T16:20:45Z"
    generation: 2
    labels:
      app: mysql
    name: mysql
    namespace: default
    resourceVersion: "5898"
    uid: 9b35dcff-9ab5-4d19-96c2-28f32ae9fed6
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mysql
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          image: mysql:8.0
          imagePullPolicy: Always
          name: 8-0-xgx2k
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-11-13T16:22:20Z"
      lastUpdateTime: "2023-11-13T16:22:20Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-11-13T16:20:45Z"
      lastUpdateTime: "2023-11-13T16:22:20Z"
      message: ReplicaSet "mysql-6dcd954f9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2023-11-13T16:25:46Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: mysql
    name: mysql
    namespace: default
    resourceVersion: "7847"
    uid: c84bbc0e-b6c3-4cc7-b325-835deb5f0397
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.16.14.144
    clusterIPs:
    - 10.16.14.144
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31103
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.27.234.164
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
