apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-11-13T16:36:00Z"
    generation: 1
    labels:
      app: user
    name: user
    namespace: default
    resourceVersion: "12388"
    uid: bc24c0e3-03a3-4c22-84c8-f76a90a50115
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: user
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: user
      spec:
        containers:
        - image: sinchangarai/user-image:1.0
          imagePullPolicy: IfNotPresent
          name: user-image
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-11-13T16:36:06Z"
      lastUpdateTime: "2023-11-13T16:36:06Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-11-13T16:36:00Z"
      lastUpdateTime: "2023-11-13T16:36:06Z"
      message: ReplicaSet "user-84d8b99cb8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2023-11-13T16:38:01Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: user
    name: user
    namespace: default
    resourceVersion: "13523"
    uid: a37b058a-1828-45a4-8592-f44df029d5ad
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.16.7.117
    clusterIPs:
    - 10.16.7.117
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30414
      port: 8001
      protocol: TCP
      targetPort: 8001
    selector:
      app: user
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.170.240.41
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
