name: User microservice CI/CD
on:
  workflow_dispatch:
    inputs:
      test-input:
        description: "Test input"
        default: ""
        required: false

jobs:
    user_microservice_prep:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'gradle'

            - name: Build jar file with gradle wrapper
              run: |
                ./gradlew build -x test
                tee

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: sinchangarai
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: sinchangarai/user-image:ci

